if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $HOME/.config/zsh/exports
# oh-my-zsh plugins and config
plugins=(
  aws
  brew
  direnv
  docker
  gcloud
  git
  git-extras
  kubectl
  zsh-nvm
  history-substring-search
)

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

# completion
source <(kubectl completion zsh)
source <(stern --completion=zsh)

# asdf-vm
. $(brew --prefix asdf)/libexec/asdf.sh

# JAVA HOME
export JAVA_HOME=`/usr/libexec/java_home -v 15`

# aliases
source $HOME/.config/zsh/aliases

# add zsh external plugins
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# To customize prompt, run `p10k configure` or edit .config/zsh/.p10k.zsh.
[[ ! -f .config/zsh/.p10k.zsh ]] || source .config/zsh/.p10k.zsh
export PATH="/usr/local/opt/libpq/bin:$PATH"
export PATH="/usr/local/opt/binutils/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
