format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$env_var\
$cmd_duration\
$custom\
$line_break\
$time\
$status\
$character"""

[aws]
disabled = false
