return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "hcl",
        "terraform",
        -- "yaml",
        "bash",
        "comment",
        "dockerfile",
        "fish",
        "gomod",
        "gosum",
        "make",
        "regex",
        "vim",
        "typescript",
        "javascript",
        "go",
        "markdown",
        "lua",
        "html",
        "css",
        "jq",
        "json",
        "kotlin",
        "python",
        "sql",
        "toml",
      },
    },
  },
}
